commands:
  win:
    permittedIn:
      - bot
      - game
    activateOn:
      - ПОБЕДА
  flip:
    permittedIn:
      - bot
      - chat
      - game
    activateOn:
      - ФЛИП
  upgrade:
    permittedIn:
      - chat
      - bot
    activateOn:
      - АП
      - АПГРЕЙД
  profile:
    permittedIn:
      - chat
      - bot
    activateOn:
      - П
      - ПРОФ
  showCards:
    permittedIn:
      - chat
      - bot
    activateOn:
      - КАРТА
      - К
  tutorial:
    permittedIn:
      - bot
    activateOn:
      - ОБУЧЕНИЕ
      - О
  shop:
    permittedIn:
      - chat
      - bot
    activateOn:
      - МАГАЗИН
      - М
  give:
    permittedIn:
      - chat
      - bot
      - admins
    activateOn:
      - ДАТЬ
  remove:
    permittedIn:
      - chat
      - bot
      - admins
    activateOn:
      - СНЯТЬ
      - УБРАТЬ
  chance:
    permittedIn:
      - chat
      - bot
    activateOn:
      - ШАНС
  destroy:
    permittedIn:
      - chat
      - bot
    activateOn:
      - РАЗОРВАТЬ
      - РАЗР
  varenik:
    permittedIn:
      - bot
    activateOn:
      - ВАРЕНИК
      - АМИРХАН
  varenik:
    permittedIn:
      - bot
    activateOn:
      - ВАРЕНИК
      - АМИРХАН
  leha:
    permittedIn:
      - bot
    activateOn:
      - ЛЕХА
  gerych:
    permittedIn:
      - bot
    activateOn:
      - ГЕРЫЧ
      - ГЕРМАН
  pack_dialog:
    permittedIn:
      - chat
      - bot
    activateOn:
      - ПАКИ
  removeKB:
    permittedIn:
      - chat
    activateOn:
      - УБРАТЬКЛАВУ
  game:
    permittedIn:
      - bot
    activateOn:
      - ИГРА
    
  

subOptions:
  judge:
    activateOn:
      - СУДЬЯ
  player:
    activateOn:
      - ИГРОК
  stop:
    activateOn:
      - СТОП
  rarity:
    activateOn:
      - Р
      - РЕД
      - РЕДКОСТЬ
  level:
    activateOn:
      - УР
      - УРОВЕНЬ
  repeats:
    activateOn:
      - ПОВТОРКИ
      - ПОВТ
  scraps:
    activateOn:
      - ОБР
      - ОБРЫВКИ
  balance:
    activateOn:
      - БАЛАНС
      - БАЛ
  pack:
    activateOn:
      - ПАК
  cards:
    activateOn:
      - КАРТА
      - К
  win:
    activateOn:
      - ПОБЕДА
  lose:
    activateOn:
      - ПОРАЖЕНИЕ
  
commandCall:
  - '.'
  - '/'
  - '#'
  - '!'

notPermitted: >
  Здесь нельзя использовать эту команду