status:
  - Шиноби
  - Саннин
  - Хокаге
  - Админ
main:
  greeting:
    message: >
      Приветствую тебя, Шиноби.



      Добро пожаловать, в мир карточных боёв по культовому аниме "Наруто"



      Перед началом игры нужно прочитать правила https://vk.com/topic-195428368_41289323



      Чтобы получить карты нажми на соответствующую кнопку



      Отлично,ты готов к боям
      "Карточные бои" проходят в беседе "Рейтинг": https://vk.me/join/AJQ1dxOp2SCBSf48YjoMLume



      Найти противника ты можешь в беседе "Флуд": https://vk.me/join/AJQ1d2lVthetszYczBAAd7mx
    keyboard: >
      {
      "buttons": [
      [
      {
        "action": {
          "type": "text",
          "label": "Добавить карты",
          "payload": "[{\"addCardsPool\":[1,2,3]},{\"dialog\":\"profile\"}]"
        },
        "color": "primary"
      }
      ]
      ]
      }

  main:
    message: "Тест главного сообщения"
    keyboard: '
{
  "buttons": [
    [
      {
        "action": {
          "type": "text",
          "label": "Профиль",
          "payload": "{\"dialog\":\"profile\"}"
        },
        "color": "primary"
      }
    ],
    [
      {
        "action": {
          "type": "text",
          "label": "Обучение",
          "payload": "{\"dialog\":\"tutorial\"}"
        },
        "color": "primary"
      }
    ]
  ]
}
        '

  profile:
    message: >
      Ваш статус: {status}

      Ваш ранг: {rank}

      Ваш баланс: {balance}

      Количество обрывков: {scraps}

      Осталось боев: {battles}
      
    keyboard: >
      {
      "buttons": [
      [
      {
        "action": {
          "type": "text",
          "label": "Магазин",
          "payload": "{\"dialog\":\"shop\"}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "Коллекции",
          "payload": "{\"dialog\":\"collection\"}"
        },
        "color": "primary"
      }
      ],
      [
      {
        "action": {
          "type": "text",
          "label": "Прокачка",
          "payload": "{\"upgrade\":\"\"}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "Паки",
          "payload": "{\"dialog\":\"packs\"}"
        },
        "color": "primary"
      }
      ],
      [
      {
        "action": {
          "type": "text",
          "label": "Найти игру",
          "payload": "{\"dialog\":\"game_search\"}"
        },
        "color": "primary"
      }
      ]
      ]
      }

  shop:
    message: >
      Магазин



      Обычный пак: 100 монет

      Шансы выпадения:
      
      85% - обычная
      
      15% - редкая



      Редкий пак: 150 монет

      Шансы выпадения: 
      
      5% - обычная
      
      85% - редкая
      
      10% - эпическая



      Эпический пак: 200 монет

      Шансы выпадения:
      
      92% - эпическая
      
      8% - легендарная
      
      
      
      Рандом пак: 170 монет
      
      Шансы выпадения: 
      
      Любая карта 1 уровня



      Ваш баланс: {balance}
    keyboard: >
        {
        "buttons": [
        [
        {
        "action": {
          "type": "text",
          "label": "Обычный",
          "payload": "{\"getPack\":0}"
        },
        "color": "primary"
        },
        {
        "action": {
          "type": "text",
          "label": "Редкий",
          "payload": "{\"getPack\":1}"
        },
        "color": "primary"
        },
        {
        "action": {
          "type": "text",
          "label": "Эпический",
          "payload": "{\"getPack\":2}"
        },
        "color": "primary"
        },
        {
        "action": {
          "type": "text",
          "label": "Случайный",
          "payload": "{\"getPack\":3}"
        },
        "color": "primary"
        }
        ],
        [
        {
        "action": {
          "type": "text",
          "label": "Назад",
          "payload": "{\"dialog\":\"profile\"}"
        },
        "color": "primary"
        }
        ]
        ]
        }

  notEnoughMoney:
    message: >
      У вас не хватает денег. Продолжайте играть, чтобы заработать

  notEnoughScraps:
    message: >
      У вас не хватает обрывков. 
  
  purchase:
    message: > 
      Вам выпала карта 
      
      {card}

      Поздравляем!

  upgraded:
    message: >
      Улучшена карта 
      


      {card} 

  upgradeFail:
    message: >
      У вас нет подходящих карт для улучшения

  collection:
    message: >
      Выберите уровень

    keyboard: '
    {
  "buttons": [
    [
      {
        "action": {
          "type": "text",
          "label": "1 уровень",
          "payload": "{\"showCards\":{\"level\": \"1\"}}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "2 уровень",
          "payload": "{\"showCards\":{\"level\": \"2\"}}"
        },
        "color": "primary"
      }
    ],
    [
      {
        "action": {
          "type": "text",
          "label": "Назад",
          "payload": "{\"dialog\":\"profile\"}"
        },
        "color": "primary"
      }
    ]
  ]
}
    '
  noCards:
    message: >
      У вас нет карт  такого типа

  noCardsPlr:
    message: У этого игрока нету карт



  poolcards:
    message: >
      Вам были выданы следующие карты

      {card}
      
      
      
      Получить их можно в коллекции
    keyboard: '
    {
  "buttons": [
    [
      {
        "action": {
          "type": "text",
          "label": "Назад",
          "payload": "{\"dialog\":\"profile\"}"
        },
        "color": "primary"
      }
    ]
  ]
}   
    '



  firstPlayer:
    message: >
      Ходит первый игрок

  secondPlayer:
    message: >
      Ходит второй игрок

  profile_inline_otheruser:
    message: >
      Его статус: {status}

      Его ранг: {rank}

      Осталось боев: {battles}

  shop_inline:
    keyboard: '
{
  "buttons": [
    [
      {
        "action": {
          "type": "text",
          "label": "Обычный",
          "payload": "{\"getPack\":0}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "Редкий",
          "payload": "{\"getPack\":1}"
        },
        "color": "primary"
      }
    ],
    [
      {
        "action": {
          "type": "text",
          "label": "Эпический",
          "payload": "{\"getPack\":2}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "Случайный",
          "payload": "{\"getPack\":3}"
        },
        "color": "primary"
      }
    ]
  ],
  "inline": true
}
    '
    message: >
      Магазин



      Обычный пак: 100 монет

      Шансы выпадения:
      
      85% - обычная
      
      15% - редкая



      Редкий пак: 150 монет

      Шансы выпадения: 
      
      5% - обычная
      
      85% - редкая
      
      10% - эпическая



      Эпический пак: 200 монет

      Шансы выпадения:
      
      92% - эпическая
      
      8% - легендарная
      
      
      
      Рандом пак: 170 монет
      
      Шансы выпадения: 
      
      Любая карта 1 уровня



      Ваш баланс: {balance}

  varenik:
    message: >
      Все это время Саня просто пинал хуи

  leha: 
    message: >
      400 тонн золота грезят о нем

      Создал карты и механики. PR менеджер

  gerych:
    message: >
      Если ты создал вселенную, то в ней ты сильнее всех

      Технарь - написал бота и держит сервер с ним

  packs:
    message: >
      Ваши паки:

      Обычные: {packs[0]}

      Редкие: {packs[1]}

      Эпические: {packs[2]}

      Рандом: {packs[3]}

    keyboard: '
    {
  "buttons": [
    [
      {
        "action": {
          "type": "text",
          "label": "Обычный",
          "payload": "{\"openPack\": 0}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "Редкий",
          "payload": "{\"openPack\": 1}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "Эпический",
          "payload": "{\"openPack\": 2}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "Рандом",
          "payload": "{\"openPack\": 3}"
        },
        "color": "primary"
      }
    ],
    [
      {
        "action": {
          "type": "text",
          "label": "В профиль",
          "payload": "{\"dialog\": \"profile\"}"
        },
        "color": "primary"
      }
    ]
  ]
}   
    '
  noPack:
    message: >
      У вас нет этого пака

  cantError:
    message: >
      Воу... А я так не могу...

  cardDoesNotExist:
    message: >
      Такой карты пока не существует

  wrongNumber:
    message: >
      Упс... А номер неправильный

  noDestoyableCards:
    message: >
      Союз нерушимый республик свободных...

      Ой, я имел в виду ваши карты

  gotPack:
    message: >
      Перейти к пакам?

    keyboard: '
    {
  "buttons": [
    [
      {
        "action": {
          "type": "text",
          "label": "К пакам",
          "payload": "{\"dialog\": \"packs\"}"
        },
        "color": "primary"
      }
    ],
    [
      {
        "action": {
          "type": "text",
          "label": "В магазин",
          "payload": "{\"dialog\": \"shop\"}"
        },
        "color": "primary"
      }
    ],
    [
      {
        "action": {
          "type": "text",
          "label": "В профиль",
          "payload": "{\"dialog\": \"profile\"}"
        },
        "color": "primary"
      }
    ]
  ]
}
    '

  packs_inline:
    message: >
      Ваши паки:

      Обычные: {packs[0]}

      Редкие: {packs[1]}

      Эпические: {packs[2]}

      Рандом: {packs[3]}

    keyboard: '
    {
  "buttons": [
    [
      {
        "action": {
          "type": "text",
          "label": "Обычный",
          "payload": "{\"openPack\": 0}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "Редкий",
          "payload": "{\"openPack\": 1}"
        },
        "color": "primary"
      }
    ],
    [
      {
        "action": {
          "type": "text",
          "label": "Эпический",
          "payload": "{\"openPack\": 2}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "Рандом",
          "payload": "{\"openPack\": 3}"
        },
        "color": "primary"
      }
    ]
  ], "inline": true
}   
    '
  kb_placeholder:
    message: Изыйди, клава
    keyboard: '{"buttons":[]}'

  find_lobby:
    message: Идет поиск лобби. Пожалуйста подождите
    keyboard: '
    {
  "buttons": [
    [
      {
        "action": {
          "type": "text",
          "label": "Остановить поиск",
          "payload": "{\"game\":\"stop\"}"
        },
        "color": "primary"
      }
    ]
  ]
}
    '

  cancel_search:
    message: >
      Поиск лобби отменен

    keyboard: '
      {
      "buttons": [
      [
        {
        "action": {
          "type": "text",
          "label": "В профиль",
          "payload": "{\"dialog\":\"profile\"}"
        },
        "color": "primary"
        }
        ]
        ]
        }
    '
  game_search:
    message: >
      Выберите вашу роль

    keyboard: '
{
  "buttons": [
    [
      {
        "action": {
          "type": "text",
          "label": "Игрок",
          "payload": "{\"game\":\"player\"}"
        },
        "color": "primary"
      },
      {
        "action": {
          "type": "text",
          "label": "Судья",
          "payload": "{\"game\":\"judge\"}"
        },
        "color": "primary"
      }
    ],
    [
      {
        "action": {
          "type": "text",
          "label": "Любая",
          "payload": "{\"game\":\"random\"}"
        },
        "color": "primary"
      }
    ],
    [
      {
        "action": {
          "type": "text",
          "label": "Назад",
          "payload": "{\"dialog\":\"profile\"}"
        },
        "color": "primary"
      }
    ]
  ]
}
    '
  nobattles:
    message: >
      У вас нет боев. Вы сможете играть снова завтра после 12:00 по МСК

    keyboard: '
      {
      "buttons": [
      [
        {
        "action": {
          "type": "text",
          "label": "В профиль",
          "payload": "{\"dialog\":\"profile\"}"
        },
        "color": "primary"
        }
        ]
        ]
        }
    '
  nouser:
    message: >
      Данного пользователя нет в базе данных. 

  dialogError:
    message: >
      Ой, а такого диалога нет...

  lobbyReady:
    message: >
      Лобби в сборе! Нажмите "Готов", чтобы подтвердить свою готовность
    keyboard: '
{
  "one_time": true,
  "buttons": [
    [
      {
        "action": {
          "type": "callback",
          "label": "Готов",
          "payload": "{\"game\": \"ready\"}"
        },
        "color": "primary"
      }
    ]
  ]
}
    '
  
  lobbyActive:
    message:
      Все готовы! Можете начинать игру

  AFKcomp:
    message: >
      Один из игроков не был готов, поэтому вам были даны монеты

  AFKpun:
    message: >
      Вы задерживали игроков, которые хотели поиграть, поэтому у вас отняли часть монет



