battle:
  count:
    - 5
    - 6
    - 7
    - 32767

  win:
    -
      balance: 10
      scraps: 3
    -
      balance: 10
      scraps: 3
    -
      balance: 15
      scraps: 3
    -
      balance: 10000
      scraps: 5000 

  lose:
    -
      balance: 5
    -
      balance: 10
    -
      balance: 10
    -
      balance: 10000 

streak:
  count:
    win:
      - 5
      - 5
      - 5
      - 5

    lose:
      - 5
      - 5
      - 5
      - 5

  reward:
    win:
      -
        balance: 20
      -
        balance: 20
      -
        balance: 20
      -
        balance: 20

    lose:
      -
        scraps: 5
      -
        scraps: 5
      -
        scraps: 5
      -
        scraps: 5




packSettings:
  - 
    price: 100
    rarities:
      '2': 15
  - 
    price: 150
    rarities:
      '2': 85
      '3': 10
  - 
    price: 200
    rarities:
      '3': 92
      '4': 8
  - 
    price: 170
    rarities:
      '0'


upgrade: 
  scrapCosts:
    # Formula
    #
    # defaultPrice + rarityRatio*(level^dafaultPower)

    defaultPrice: 20

    defaultPower: 1.585

    rarityRatios:
      '-1': 45
      '1': 5
      '2': 10
      '3': 15
      '4': 20

  repeatsNeeded:
    '-1': 
      - 2
      - 2
    '1': 
      - 3
      - 2
    '2': 
    - 3
    - 2
    '3': 
      - 2
      - 2
    '4': 
      - 2
      - 2

breakPrice:
  '1': 5
  '2': 8
  '3': 15
  '4': 25
  '5': 25
  '-1': 50

defaultPremium: 7
minimumCards: 3




readyWait: 120







AFK:
  compensate: 5
  punish: 5
