expSettings:
  expAdd:
    -
      win: 15
      lose: 5
    -
      win: 15
      lose: 10
    -
      win: 10
      lose: 10
    -
      win: 8
      lose: 10
  expLevels:
    '0':
      name: Ученик академии
      expGroup: 0
      reward:
        balance: 10
    '50':
      name: Выпускник
      expGroup: 0
      reward:
        balance: 30
    '75':
      name: Генин
      expGroup: 0
      reward:
        balance: 20
        scraps: 5
    '125':
      name: Экзамен на Чуунина
      expGroup: 1
      reward:
        balance: 40
        scraps: 5
    '150':
      name: Чуунин
      expGroup: 1
      reward:
        scraps: 10
    '200':
      name: Капитан Чуунинов
      expGroup: 1
      reward:
        cardPack:
          - 1
    '245':
      name: Джоунин
      expGroup: 1
      reward:
        cardPack:
          - 1
          - 0
    '270':
      name: Наставник генинов
      expGroup: 2
      reward:
        cardPack:
          - 2
    '350':
      name: АНБУ
      expGroup: 2
      reward:
        card:
          rarity: 3
    '400':
      name: Саннин
      expGroup: 2
      reward:
        cardPack:
          - 3
          - 3
    '500':
      name: Каге
      expGroup: 3
      reward:
        card: 
          rarity: 4
    '650':
      name: Мудрец
      expGroup: 3
      reward:
        card: 
          rarity: -1
